### ISSUE TITLE
Jet ID input variables

### ISSUE THREAD

**Issue by andreypz** [cmkuo/ggAnalysis#8]
The twiki for Jet ID recommendations has been updated:
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016
Specifically, in order to get the energy fractions for Jet ID one has to use the un-corrected jet Pt.
I'm not sure if the implementation in ggNtuples give the same result, [see lines here](https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L533-L539)
This is also discussed in [this thread on HN](https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/1723/1/1/1/1/1/1/1/2/1/1/1/1/1/1.html)

**Comment by lovedeepkaursaini** [comment]
Thanks Andrey!
I didn't know about this. So its only about MuonEnergyFraction? If so I
will correct L462 and L692/L721?



L462:
https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L462

L692:
https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L692

L721:
https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L721


Lovedeep

On Thu, Feb 9, 2017 at 10:51 AM, Andrey Pozdnyakov <notifications@github.com

**Comment by andreypz** [comment]
Hi,
First of all, I am not sure if the change is needed. If you read the [HN post from the beginning](https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/1723.html) (it's quite a lot of messages), it is not clear to me. It's possible that the fractions are in fact calculated with respect to uncorrected jets (as they should be), even if they are called from a corrected jet. Perhaps you could check that by summing them. They must sum to unity.

But if this is incorrect, then it should be fixed for all fractions, not just muon: jetNHF, jetCHF, etc

**Comment by cmkuo** [comment]
the twiki was just updated again !

Note: All fractions are calculated with the raw/uncorrected energy of the jet (only then they add up to unity). So the PF JetID has to be applied before the jet energy corrections. To do this on a MINIAOD jet, you can get them as:
            auto CHF          = jet.chargedHadronEnergy() / jet.correctedP4(0).E()  ;  
            auto NHF          = jet.neutralHadronEnergy() / jet.correctedP4(0).E()  ;  
            auto CM           = jet.chargedMultiplicity()  ;                  
            auto NM           = jet.neutralMultiplicity()  ;                  
            auto NEF          = jet.neutralEmEnergy() / jet.correctedP4(0).E()  ;      
            auto CEF          = jet.chargedEmEnergy() / jet.correctedP4(0).E()  ;      
            auto MUF          = jet.muonEnergy() / jet.correctedP4(0).E()  ;           
            auto NumConst = jet.numberOfDaughters() ;   

OR you can use the "Fraction" methods directly:

 NHF  = pfjet->neutralHadronEnergyFraction();
 NEMF = pfjet->neutralEmEnergyFraction();
 CHF  = pfjet->chargedHadronEnergyFraction();
 MUF  = pfjet->muonEnergyFraction();
 CEMF = pfjet->chargedEmEnergyFraction();
 NumConst = pfjet->chargedMultiplicity()+pfjet->neutralMultiplicity();
 NumNeutralParticles =pfjet->neutralMultiplicity();
 CHM      = pfjet->chargedMultiplicity();

**Comment by cmkuo** [comment]
I think we are fine with the PF jet ID in ggNtuple.

**Comment by andreypz** [comment]
Ok, this is good.

**Comment by cmkuo** [comment]
however, it seems to me we need to update jet PU ID.

**Comment by bartokm** [comment]
Hi all,

I've noticed that the jetID criteria for 2.7< |eta|<3 has been changed, and
it has not propagated into our code.
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016
https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L546-L548

cheers,
Márton

**Comment by cmkuo** [comment]
Hi Márton

Thanks for reporting this !
I just updated it. Can you please double check ?

Cheers
Ming

**Comment by bartokm** [comment]
Hi Ming,

The modifications are correct. But shouldn't we update the AK8JetID too? Or
for AK8 there are different criteria? It doesn't says on the twiki.

cheers,
Márton

**Comment by cmkuo** [comment]
Hi Márton

Thanks for reporting this.
It's updated 
https://github.com/cmkuo/ggAnalysis/blob/master/ggNtuplizer/plugins/ggNtuplizer_jets.cc#L707-L708

Cheers
Ming
